In [1]:
import tensorflow as tf

/Users/andy/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## 建立計算圖

In [2]:
# 建立TensorFlow常數，值為2，設定name會顯示在計算圖上
ts_c = tf.constant(2, name='ts_c')

In [3]:
ts_c

<tf.Tensor 'ts_c:0' shape=() dtype=int32>

In [4]:
# 建立TensorFlow變數，ts_c的值在+5
ts_x = tf.Variable(ts_c+5, name='ts_x')

In [5]:
# 變數必須經過執行計算圖才能看到顯示的結果
ts_x

<tf.Variable 'ts_x:0' shape=() dtype=int32_ref>

## 執行計算圖

In [6]:
# 建立Session，session代表用戶端與執行裝置間建立連結
sess = tf.Session()

In [7]:
# 初始化變數
init = tf.global_variables_initializer()
sess.run(init)

In [8]:
# 使用session執行TensorFlow常數
print('ts_c = ', sess.run(ts_c))

ts_c =  2


In [9]:
# 使用session執行TensorFlow變數
print('ts_x = ', sess.run(ts_x))

ts_x =  7


In [11]:
# 使用eval執行TensorFlow常數
print('ts_c = ', ts_c.eval(session=sess))

ts_c =  2


In [12]:
# 使用eval執行TensorFlow變數
print('ts_x = ', ts_x.eval(session=sess))

ts_x =  7


In [13]:
# 關閉session
sess.close()

### with語法

In [15]:
# 使用with語法可以不用擔心忘記關閉Session導致程式執行異常
# 在with區塊中可以使用sess變數與裝置溝通，離開with區塊自動關閉session

ts_c = tf.constant(2, name='ts_c')
ts_x = tf.Variable(ts_c+5, name='ts_x')
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('ts_c = ', sess.run(ts_c))
    print('ts_x = ', sess.run(ts_x))

ts_c =  2
ts_x =  7


## TensorFlow placeholder

In [16]:
# 希望在執行的時候才設定數值，使用placeholder
width = tf.placeholder('int32')
height = tf.placeholder('int32')
area = tf.multiply(width, height) # 相乘

In [17]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area = ', sess.run(area, feed_dict={width: 6, height: 8}))

area =  48


## TensorFlow 常用數值運算

即使是簡單的數值計算也要用到TensorFlow模組是因為如此才能具備跨平台的功能

- tf.add(x, y, name=)：加法
- tf.subtract(x, y, name=)：減法
- tf.multiply(x, y, name=)：乘法
- tfdivide(x, y, name=)：除法
- tf.mod(x, y, name=)：餘數
- tf.sqrt(x, name=)：平方
- tf.abs(x, name=)：絕對值

## TensorBoard

以視覺化方式呈現計算圖

In [22]:
width = tf.placeholder('int32', name='width')
height = tf.placeholder('int32', name='height')
area = tf.multiply(width, height, name='area')

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area = ', sess.run(area, feed_dict={width: 6, height: 8}))

area =  48


In [23]:
# 將要顯示在TensorBoard的資料寫入log檔
tf.summary.merge_all()
train_writer = tf.summary.FileWriter('log/area', sess.graph)

終端機輸入tensorboard  --logdir=/Users/andy/Documents/python/校外課程\&自我學習/Tensorflow\&Keras教學/log/area/
<br>
瀏覽器開啟http://localhost:6006 ，點選graph即可看到圖

## 建立一維&二維向量

In [24]:
# 一維
# 將list放入tf.Variable即可
ts_X = tf.Variable([0.4, 0.2, 0.4])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)

[0.4 0.2 0.4]


In [25]:
X.shape

(3,)

In [26]:
# 二維
ts_X = tf.Variable([[0.4, 0.2, 0.4]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)

[[0.4 0.2 0.4]]


In [27]:
X.shape

(1, 3)

In [28]:
# 二維
W = tf.Variable([[-0.5, -0.2],
                 [-0.3, 0.4 ],
                 [-0.5, 0.2 ]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W_array = sess.run(W)
    print(W_array)

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]


In [29]:
W_array.shape

(3, 2)

## 矩陣基本運算

In [31]:
# 矩陣乘法
X = tf.Variable([[1., 1., 1.]])
W = tf.Variable([[-0.5, -0.2],
                 [-0.3, 0.4 ],
                 [-0.5, 0.2 ]])

XW = tf.matmul(X, W)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XW))

[[-1.3  0.4]]


In [33]:
# 矩陣加法
b = tf.Variable([[0.1, 0.2]])
XW = tf.Variable([[-1.3, 0.4]])

Sum = b+XW

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print("SUM: ", sess.run(Sum))

SUM:  [[-1.1999999  0.6      ]]


In [34]:
# 矩陣加法與乘法
X = tf.Variable([[1., 1., 1.]])
W = tf.Variable([[-0.5, -0.2],
                 [-0.3, 0.4 ],
                 [-0.5, 0.2 ]])
b = tf.Variable([[0.1, 0.2]])

XWb = tf.matmul(X,W)+b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XWb))

[[-1.1999999  0.6      ]]
