### 神經網路模擬公式

Y = activation(X * W + b)

In [1]:
import tensorflow as tf

/Users/andy/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
# 激活函數activation使用relu
X = tf.Variable([[0.4, 0.2, 0.4]])
W = tf.Variable([[-0.5, -0.2],
                 [-0.3, 0.4 ],
                 [-0.5, 0.2 ]])
b = tf.Variable([[0.1, 0.2]])

XWb = tf.matmul(X,W)+b
y = tf.nn.relu(XWb)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb = ', sess.run(XWb))
    print('y = ', sess.run(y))

XWb =  [[-0.35999998  0.28      ]]
y =  [[0.   0.28]]


In [3]:
# 激活函數activation使用sigmoid
X = tf.Variable([[0.4, 0.2, 0.4]])
W = tf.Variable([[-0.5, -0.2],
                 [-0.3, 0.4 ],
                 [-0.5, 0.2 ]])
b = tf.Variable([[0.1, 0.2]])

XWb = tf.matmul(X,W)+b
y = tf.nn.sigmoid(XWb)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb = ', sess.run(XWb))
    print('y = ', sess.run(y))

XWb =  [[-0.35999998  0.28      ]]
y =  [[0.41095957 0.5695462 ]]


In [6]:
# 以常態分佈的亂數初始化Weight和Bias
X = tf.Variable([[0.4, 0.2, 0.4]])
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([1, 2]))
y = tf.nn.relu(tf.matmul(X,W)+b)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('W:', sess.run(W))
    print('b:', sess.run(b))
    print('y:', sess.run(y))

W: [[-0.21869557 -0.51793355]
 [ 1.2849728   0.23922022]
 [-2.20566     0.9302928 ]]
b: [[-1.7342868  0.5754654]]
y: [[0.        0.7882531]]


In [9]:
# 縮減上述寫法，只執行一次session run
X = tf.Variable([[0.4, 0.2, 0.4]])
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([1, 2]))
y = tf.nn.relu(tf.matmul(X,W)+b)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    (_b,_W,_y) = sess.run((b,W,y))
    print('W:', _W)
    print('b:', _b)
    print('y:', _y)

W: [[ 0.81867784 -0.47310334]
 [-1.0845878   0.02371043]
 [ 2.4391391  -0.09180546]]
b: [[ 0.18670943 -1.6524714 ]]
y: [[1.2729187 0.       ]]


### 改以placeholder傳入x值

In [10]:
import numpy as np
X = tf.placeholder("float", [None, 3]) # 前面定義資料型態，後面代表矩陣大小
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([1, 2]))
y = tf.nn.relu(tf.matmul(X,W)+b)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4, 0.2, 0.4]]) # 建立X_array
    (_b,_W,_y) = sess.run((b,W,y), feed_dict={X:X_array})
    print('W:', _W)
    print('b:', _b)
    print('y:', _y)

W: [[-0.8493311  -1.4771539 ]
 [ 0.2618949   0.40300435]
 [-0.14252637 -0.0699286 ]]
b: [[ 1.3195693  -0.15323608]]
y: [[0.9752053 0.       ]]


### 建立layer函數

In [2]:
def layer(output_dim, input_dim, inputs, activation=None):
    W = tf.Variable(tf.random_normal([input_dim, output_dim]))
    b = tf.Variable(tf.random_normal([1, output_dim]))
    XWb = tf.matmul(inputs, W) + b
    if activation is None: # 如果沒有傳入激活函數就不使用
        outputs = XWb
    else:
        outputs = activation(XWb)
    return outputs

使用layer函數建立3層神經網路

In [3]:
# 輸入層4個神經元
X = tf.placeholder("float", [None, 4])

In [4]:
# 隱藏層3個神經元
h = layer(output_dim=3, input_dim=4, inputs=X, activation=tf.nn.relu)

In [5]:
# 輸出層2個神經元
y = layer(output_dim=2, input_dim=3, inputs=h)

In [7]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4, 0.2, 0.4, 0.5]]) # 建立X_array
    (layer_X, layer_h, layer_y) = sess.run((X,h,y), feed_dict={X:X_array})
    print('W:', layer_X)
    print('b:', layer_h)
    print('y:', layer_y)

W: [[0.4 0.2 0.4 0.5]]
b: [[0.        2.0594077 0.       ]]
y: [[2.0608597 0.948593 ]]


### 建立layer_debug函數

In [8]:
def layer_debug(output_dim, input_dim, inputs, activation=None):
    W = tf.Variable(tf.random_normal([input_dim, output_dim]))
    b = tf.Variable(tf.random_normal([1, output_dim]))
    XWb = tf.matmul(inputs, W) + b
    if activation is None:
        outputs = XWb
    else:
        outputs = activation(XWb)
    return outputs, W, b

In [17]:
# 輸入層4個神經元
X = tf.placeholder("float", [None, 4])

# 隱藏層3個神經元
h,W1,b1 = layer_debug(output_dim=3, input_dim=4, inputs=X, activation=tf.nn.relu)

# 輸出層2個神經元
y,W2,b2 = layer_debug(output_dim=2, input_dim=3, inputs=h)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4, 0.2, 0.4, 0.5]]) # 建立X_array
    (layer_X, layer_h, layer_y, W1, b1, W2, b2) = sess.run((X,h,y,W1,b1,W2,b2), feed_dict={X:X_array})
    print('input Layer X:');print(layer_X)
    print('W1:');print(W1)
    print('b1:');print(b1)
    print('hidden Layer h:');print(layer_h)
    print('W2:');print(W2)
    print('b2:');print(b2)
    print('output Layer h:');print(layer_y)

input Layer X:
[[0.4 0.2 0.4 0.5]]
W1:
[[-0.957348   -0.43149352  0.45813298]
 [ 1.6596817  -1.1965383  -0.49768868]
 [-0.48003554 -0.5982234  -2.3496964 ]
 [-1.773955    0.07885315 -1.7832947 ]]
b1:
[[ 0.88200456  0.5969678  -2.423311  ]]
hidden Layer h:
[[0. 0. 0.]]
W2:
[[ 2.095088   -0.28963253]
 [ 1.4626018   1.2331222 ]
 [ 0.34808496  0.4087256 ]]
b2:
[[ 0.13241108 -0.29559785]]
output Layer h:
[[ 0.13241108 -0.29559785]]
